using static System.Console;

public class Program_UI
{
    // Repository setup
}

public Program_UI()
{
    SeedData();
    // Repository
}

public void Run();
{
    RunApplication();
}

private void RunApplication()
{
    while (IsRunning)
    {
        System.Console.WriteLine("Welcome to The Myth of Sisyphus - press any key to continue...\n");

        Console.ReadKey();
        Console.Clear();
        
        // At this point in the game music starts playing

        System.Console.WriteLine("The time is: 'It's tomorrow at 9:00am' It's a beautiful day, you can't wait to go outside and enjoy your day off! Oh sh*t...your tags are expired!\n"
        + "1. Be productive!\n"
        + "2. Naaaah~ I'm going to enjoy my day off!\n"

        string? input = Console.ReadLine();

        switch (input)
        {
            case "1":

        }

        // Create different "loads" for the paths

        );

    }
}